name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ---------- NEW STEP ----------
      - name: Run process_logs.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/process_logs.py

      # You can keep your tests if you want
      - name: Run tests
        run: pytest || true

      # ---------- OPTIONAL: upload CSV ----------
      - name: Upload CSV
        uses: actions/upload-artifact@v3
        with:
          name: build_data
          path: data/build_data.csv
