name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run process_logs.py
        run: python scripts/process_logs.py

      - name: Train ML model
        run: python scripts/train_model.py

      - name: List data folder (debug)
        run: ls -R data

      - name: List models folder (debug)
        run: ls -R models

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_data
          path: data/build_data.csv

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained_model
          path: models/model.pkl
